### ISSUE TITLE
Spotify Connect?

### ISSUE THREAD

**Issue by Mojas84** [RuurdBijlsma/Music#1]
How to login to spotify credentials i add but in log write browser write error URL direct

**Comment by RuurdBijlsma** [comment]
One of the redirect urls in the Spotify api project settings must be http://localhost:38900

I think that's what's causing your issue

**Comment by RuurdBijlsma** [comment]
did that solve it?

**Comment by Mojas84** [comment]
Yes but app is slow and pictures on rainmeter widget send in bad quality....

**Comment by RuurdBijlsma** [comment]
ok i close issue. The album art is a link to the highest res image spotify has so that's probably a rainmeter issue
