### ISSUE TITLE
Enterprise Linux support

### ISSUE THREAD

**Issue by stellessia** [RuurdBijlsma/Music#13]
Hello, I really liked your music client. However, it's unclear how to install it on Enterprise Linux (a.k.a RHEL and it's derivatives that use RPM, they have compatibility) distributions like RHEL, Fedora, *SUSE, CentOS, Oracle Linux, AlmaLinux, Rocky Linux without building anything. Can you make a version for RPM based distributions? I recommend building it on Rocky Linux 8 because it's more reliable unlike non-stream CentOS which is now outdated too much. Thanks in advance.

**Comment by RuurdBijlsma** [comment]
I dont have this OS so I won't be able to build or test it, sorry
