### ISSUE TITLE
Doesn't work.

### ISSUE THREAD

**Issue by Faccin27** [RuurdBijlsma/Music#17]
Error no getdominant color import, i think. pls fix for we <3

**Comment by RuurdBijlsma** [comment]
should  be fixed in latest update (6.11, check settings page to see current version), if not tell me

**Comment by Faccin27** [comment]
error on get dominant color

15:52:37.083 > 5d5R5A3dkYJGnnOKt68bF5
Error occurred in handler for 'getDominantColor': TypeError: ColorThief.getPalette is not a function
    at NodeFunctions.getDominantColor (C:\Users\Faccin\projects\Music\out\main\index.js:299:35)
    at C:\Users\Faccin\projects\Music\out\main\index.js:625:56
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:79681)
    at WebContents.emit (node:events:514:28)

**Comment by Faccin27** [comment]
its on the last version 6.11

**Comment by Faccin27** [comment]
fixed. Thx bro, Do you want to make it work on android and IOS?

**Comment by RuurdBijlsma** [comment]
> fixed. Thx bro, Do you want to make it work on android and IOS?

No that would require a complete rebuild. I personally only use it on desktop. Nice to hear it's fixed
