### ISSUE TITLE
limit tracks in Playlist

### ISSUE THREAD

**Issue by Maccilol** [RuurdBijlsma/Music#18]
100 tracks is the limit in playlist, this is a bug?

![Screenshot (278)](https://github.com/user-attachments/assets/bd4b8a2f-db8d-4051-921b-dedce6a4578c)
![Screenshot (279)](https://github.com/user-attachments/assets/3c8eb41f-8d0e-4dc7-beb2-e88b009c83e2)

**Comment by RuurdBijlsma** [comment]
should be fixed with the latest release https://github.com/RuurdBijlsma/Music/releases/tag/v6.11.1

**Comment by Maccilol** [comment]
yep!!
