### ISSUE TITLE
Compatibility with mac?

### ISSUE THREAD

**Issue by AISLVE** [RuurdBijlsma/Music#2]
Love it, just wanted to know if there are plans for mac build

**Comment by AISLVE** [comment]
<img width="1512" alt="Screenshot" src="https://github.com/RuurdBijlsma/Music/assets/121119257/9996536b-14f1-44f0-851d-93cdf0bf3098">

**Comment by RuurdBijlsma** [comment]
you can get spotify keys from their site, explanation in the readme of this project https://github.com/RuurdBijlsma/Music#readme

**Comment by RuurdBijlsma** [comment]
I pushed a small change that should hide the native mac buttons in the title bar

**Comment by RuurdBijlsma** [comment]
Do you have ffmpeg in your path? For windows it gets ffmpeg automatically, but I found the linux builds for ffmpeg on the site i used are broken, so for non-windows i disabled automatic ffmpeg downloading.

I also pushed another small change to try to get rid of the mac os buttons

**Comment by AISLVE** [comment]
ok, i didn't download ffmpeg, thought i had it

**Comment by AISLVE** [comment]
ok, mac ones gone, but still, the music is not playing, just buffering

**Comment by AISLVE** [comment]
yes yes i checked before building, it is in the PATH

**Comment by AISLVE** [comment]
@RuurdBijlsma https://hastebin.com/share/asunuhigam.yaml

**Comment by AISLVE** [comment]
Your app was created, but some details could not be saved. when creating the app

**Comment by RuurdBijlsma** [comment]
hmm doesn't look like an easy fix

https://www.reddit.com/r/youtubedl/comments/lthfc9/certificate_verify_failed_when_downloading_from/goybrnq/

This comment suggest the issue could be an expired certificate on the server you are downloading from or an expired root certificate authority (CA) certificate on your local computer.

**Comment by RuurdBijlsma** [comment]
oops accidentally clicked close

**Comment by AISLVE** [comment]
ok, gotta go to sleep as i have an exam tomorrow

**Comment by AISLVE** [comment]
another person in https://t.me/DroidDiscussion is facing the same issue

**Comment by RuurdBijlsma** [comment]
> wanted to ask one more thing, where did u learn web develeopment

Mostly self taught but I also did a bachelor in computer science, and my high school had computer science classes starting with web development

**Comment by tusharchopra07** [comment]
> > ok, gotta go to sleep as i have an exam tomorrow
> 
> ![image](https://private-user-images.githubusercontent.com/47528708/288114168-ab3d2398-f0ee-4f1c-bc51-b22e6690f40a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3OTMwMzcsIm5iZiI6MTcwMTc5MjczNywicGF0aCI6Ii80NzUyODcwOC8yODgxMTQxNjgtYWIzZDIzOTgtZjBlZS00ZjFjLWJjNTEtYjIyZTY2OTBmNDBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDE2MTIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzNDViNzRmNzYxNzJlMTkzOWYxZjc1NDY2MDNlYzY3M2EzYWJlZTBmMWU4M2I3NDljNDYwYjRlNmVjMjllMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oSv8aWDhhowe0SZO1R880bLaZpN700fQQrnY5lZRDyM)

 Do you also have any exam, Good Luck 🤞🏻
