### ISSUE TITLE
The audio playback icon keeps spinning and the sound doesn't play

### ISSUE THREAD

**Issue by xiperfect** [RuurdBijlsma/Music#3]
I logged in successfully via Spotify, but when playing any audio content (it does not work) and the icon just rotates

like this 

![287468147-d4c87c7d-b3b0-40c6-a24e-e6e0567083c1](https://github.com/RuurdBijlsma/Music/assets/124534657/9273f601-41cc-4b8a-b78a-3a8b6c61cd4a)

**Comment by RuurdBijlsma** [comment]
1. What OS are you using? 
2. if you're not using windows do you have ffmpeg in your PATH?
3. could you post logs? ctrl shift i to open dev tools, then click the log tab

**Comment by RuurdBijlsma** [comment]
sorry i  meant console tab, but i can see it in your screenshot. there's no error there so the error message must be in the node logs, which isnt visible from here. If you run the program in dev mode you will be able to see the log and I might be able to fix it or help you.

To do this you need to have Node and Git installed.

In a terminal 

1. clone the repo: `git clone https://github.com/ruurdbijlsma/Music`
2. `cd Music`
3. `npm install`
4. `npm run dev`

The program will now start, try to play something and if it doesnt work again copy the log from the terminal where you started the program from. There should be an error there.

**Comment by xiperfect** [comment]
> hmm interesting, not sure how to fix it then :( I do see that a long playlist name breaks the UI so i'll try to fix that

It seems that the launch of the program was a few days ago. Problems are likely to occur. Do not worry and continue. We support you. Thank you and I wish you good luck.
