### ISSUE TITLE
api

### ISSUE THREAD

**Issue by senolfndk** [RuurdBijlsma/Music#4]
![Ekran görüntüsü 2023-12-02 235540](https://github.com/RuurdBijlsma/Music/assets/52818836/14014507-46b3-48eb-a376-b925b184a73f)
😒

**Comment by senolfndk** [comment]
> yönlendirme URL'sini Spotify API projenizde [http://localhost:38900 olarak](http://localhost:38900) ayarladınız mı ?

okay, done

**Comment by RuurdBijlsma** [comment]
can you login to spotify now?

**Comment by senolfndk** [comment]
> can you login to spotify now?

Ok I logged in

**Comment by RuurdBijlsma** [comment]
nice
