### ISSUE TITLE
spotify API redirect

### ISSUE THREAD

**Issue by xtprion** [RuurdBijlsma/Music#5]
I followed the tutorial but still can't login
![image](https://github.com/RuurdBijlsma/Music/assets/46372297/9b81135d-7324-4aac-8408-d0e8909d2222)
![image](https://github.com/RuurdBijlsma/Music/assets/46372297/8d990b4f-b6a2-46ec-9d8c-0da90cf2a7f0)

**Comment by MajnuRangeela** [comment]
Same Issue

**Comment by Iam-Sherlock** [comment]
remove the Slash at the end of redirect URLs (38900)

**Comment by RuurdBijlsma** [comment]
Yep removing the slash should do it
