### ISSUE TITLE
Buffering Issue 

### ISSUE THREAD

**Issue by JunaiseJ** [RuurdBijlsma/Music#9]
the program is fine logged in and everything but i am not bale to play any songs in it it just keeps buffering so from previous such issues i tried running the log codes and here is what i got 
![image_2023-12-04_181215617](https://github.com/RuurdBijlsma/Music/assets/152873670/b019c1ec-5419-41e3-961f-685aa715da38)
[Logs.txt](https://github.com/RuurdBijlsma/Music/files/13546013/Logs.txt)
please look into it i really luv your project and its so good to my setup

**Comment by RuurdBijlsma** [comment]
when you cloned it you got an error that the music folder already exists, so you have to clone it to somewhere else. When in C:\Users\Junai there's already a Music folder, so try going to Documents first for example.
So `cd Documents`
then do clone, npm install, etc.

**Comment by JunaiseJ** [comment]
![image_2023-12-06_192004776](https://github.com/RuurdBijlsma/Music/assets/152873670/9523c985-a2c8-4cab-ad78-5542514b979b)
yeah it was my fault i actually didnt clone the repo properly that why its didnt find the .jason package thank god you said to change the folder so i remembered thanks so much man i love this work of yours just made for my pc but please consider these issues not to blame you but its just like some suggestions for fututre updates 
1) can you add a touch based song selections for example in a playlist if i want to play 8th song i have to come by each song by song but instead if it was like just tap on the song and the song plays that would be so good
2) sometimes rarely while selecting new playlist the same buffering problem arises so i have to go through all the process and run dev mode again so could you look into it 
3) while selecting each song there is a pause to load the song like an about 15 sec soo could you look onto that too 
    Rest all is fine this application is a GEM i love it so much hoping for further fixes

**Comment by JunaiseJ** [comment]
ohh cool 
yeah yesterday i realized that double click one sorry for finding it late my bad
and that second issues is fixed yeah i restarted my pc and checked for that buffering issues its fixed new playlists are also playing fine without any issues
and third issues I didn't know it used to download and process the song i thought it might be through web client if it download then fine 
only issues is that while on a fresh install we have to enable developer mode but it is fine for the gorgeous looks of this app other than this, this works so good man as i said "A GEM"
